version: 0.0.{build}
clone_depth: 1

environment:
    MSVC_DEFAULT_OPTIONS: ON
    matrix:
     #- gen: "MinGW Makefiles"
     #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - gen: "Visual Studio 14 2015"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - gen: "Visual Studio 15 2017"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      - gen: "Visual Studio 15 2017"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017 Preview

init:
  - cmake --version

before_build:
  - git submodule update --init

build_script:
  - IF "%gen%" == "MinGW Makefiles" set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - IF "%gen%" == "MinGW Makefiles" set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
  - IF "%gen%" == "MinGW Makefiles" md debug_64
  - IF "%gen%" == "MinGW Makefiles" cd debug_64
  - IF "%gen%" == "MinGW Makefiles" cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
  - IF "%gen%" == "MinGW Makefiles" cmake --build . -- -k -j2
  - IF "%gen%" == "MinGW Makefiles" cd ..
  - IF "%gen%" == "MinGW Makefiles" md release_64
  - IF "%gen%" == "MinGW Makefiles" cd release_64
  - IF "%gen%" == "MinGW Makefiles" cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..
  - IF "%gen%" == "MinGW Makefiles" cmake --build . -- -k -j2
  - IF "%gen%" == "MinGW Makefiles" cd ..

  - IF "%gen%" == "MinGW Makefiles" set PATH=%PATH%;C:\Program Files\Git\usr\bin
  - IF "%gen%" == "MinGW Makefiles" cd debug_64/tests
  - IF "%gen%" == "MinGW Makefiles" ctest --output-on-failure -j
  - IF "%gen%" == "MinGW Makefiles" cd ..
  - IF "%gen%" == "MinGW Makefiles" cd release_64/tests
  - IF "%gen%" == "MinGW Makefiles" ctest --output-on-failure -j
  - IF "%gen%" == "MinGW Makefiles" cd ..
  - IF "%gen%" == "MinGW Makefiles" appveyor exit

  - md debug_32
  - cd debug_32
  - cmake -G "%gen%" ..
  - cmake --build . --config Debug -- /maxcpucount
  - cd tests
  - ctest --output-on-failure -C Debug -j
  - cd ..
  - cd ..

  - md release_32
  - cd release_32
  - cmake -G "%gen%" ..
  - cmake --build . --config Release -- /maxcpucount
  - cd tests
  - ctest --output-on-failure -C Release -j
  - cd ..
  - cd ..

  - md debug_64
  - cd debug_64
  - cmake -G "%gen% Win64" ..
  - cmake --build . --config Debug -- /maxcpucount
  - cd tests
  - ctest --output-on-failure -C Debug -j
  - cd ..
  - cd ..

  - md release_64
  - cd release_64
  - cmake -G "%gen% Win64" ..
  - cmake --build . --config Release -- /maxcpucount
  - cd tests
  - ctest --output-on-failure -C Release -j
  - cd ..
  - cd ..

  - if "%gen%" == "Visual Studio 15 2017" md analysis
  - if "%gen%" == "Visual Studio 15 2017" cd analysis
  - if "%gen%" == "Visual Studio 15 2017" cmake -G "%gen% Win64" ..
  - if "%gen%" == "Visual Studio 15 2017" cmake --build . --config Debug -- /maxcpucount /p:RunCodeAnalysis=true
  - if "%gen%" == "Visual Studio 15 2017" cd ..
